// Generated by https://quicktype.io
export interface Tarea {
    _id:string,
    titulo:string,
    descripcion:string,
    fechaCreacion:Date,
    estado: string,
    idUsuario:string,
    importancia:number
}