// Generated by https://quicktype.io
export interface Tarea {
    id:number,
    titulo:string,
    descripcion:string,
    fechaCreacion:Date,
    estado: string,
    idUsuario:number,
    importancia:number
}